chore:  添加新任务
deepin-community/coding-quarter pull request #1
Opened 2022-11-07 05:44 UTC by xzl01

添加dtk文档相关任务

2022-11-07 06:09 UTC, BLumia requested changes

2022-11-07 06:09 UTC, BLumia commented on 1.普通难度/[写文档]dtk文档国际化标准化/文档2.md
> +- [ ]  更新文档使用示例（加分项）
```suggestion
- [ ] 在修改文档时发现并修正现有文档中的错误或者其他问题（加分项）
- [ ] 增加或更新文档使用示例（加分项）
```

2022-11-07 06:09 UTC, BLumia commented on 1.普通难度/[写文档]dtk文档国际化标准化/文档1.md
> +关于doxygen相关格式问题可以在github上咨询@BLumia，相信他也会乐意解决你的相关问题的。
```suggestion
关于doxygen相关格式问题，若在根据官方文档尝试后仍未解决，则可以在github上创建新的 Discussion 讨论主题，并 @xzl01 与 @BLumia，来一同探讨问题的解决方案。
```

2022-11-08 02:53 UTC, BLumia commented on 1.普通难度/[写文档]dtk文档国际化标准化/文档1.md
> +  - [ ] 更新文档使用示例（加分项）
确认下，这个是确实有层级关系吗？还是单纯的多了空格？

2022-11-08 03:04 UTC, BLumia requested changes
![image](https://user-images.githubusercontent.com/10095765/200464802-5adfc2b5-40a8-47d4-95a2-018a738fee21.png)

如果是两个不同的任务的话，建两个文件夹，类似于：

```
[写文档]dtksystemsetting文档国际化/
    README.md
[写文档]dtkcore文档国际化/
    README.md
```

这样的结构，描述任务的文件的名称为 README.md，可以在任务对应的目录里放置额外的文件作为参考文档（如果没有或者不需要放置的话可以不放）。

2022-11-08 03:04 UTC, BLumia commented on 1.普通难度/[写文档]dtk文档国际化标准化/文档1.md
> +doxygen的注释方式，详见doxygen的官方文档，要求英文注释写在代码之内，中文注释在doc文档之下，项目示例也放在doc目录下
- 官方文档：https://doxygen.nl/manual/
- Wiki 上的《C++ 项目接口文档手册》：[C++ 项目接口文档手册](https://wiki.deepin.org/C++%20%E9%A1%B9%E7%9B%AE%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3%E6%89%8B%E5%86%8C)

能提供链接的最好提供链接。

2022-11-08 05:16 UTC, BLumia commented
> 描述任务的文件的名称为 README.md

这个漏改了

2022-11-08 06:24 UTC, xzl01 commented on 1.普通难度/[写文档]dtk文档国际化标准化/文档1.md
> +doxygen的注释方式，详见doxygen的官方文档，要求英文注释写在代码之内，中文注释在doc文档之下，项目示例也放在doc目录下
我是觉得这点找资料的能力都没  还是别参加这个活动了吧（）

2022-11-08 06:44 UTC, xzl01 commented
@BLumia

2022-11-08 08:02 UTC, BLumia approved these changes

2022-11-08 08:02 UTC, merged