feat: deepin-tweak 的模块开发
deepin-community/coding-quarter pull request #11
Opened 2022-11-09 05:50 UTC by justforlxz

要求实现对 Grub 的功能定制

Log:

2022-11-09 06:11 UTC, BLumia reviewed
新增了个关于任务工作量/耗时的模板字段，可以考虑补充一下。

2022-11-10 01:52 UTC, zccrs requested changes

2022-11-10 01:52 UTC, zccrs commented on 2.进阶难度/[deepin-tweak]提供开机启动项的定制功能/README.md
> +### 任务描述
加上一下对任务工作量的预估就行了

2022-11-10 02:46 UTC, zccrs approved these changes

2022-11-10 02:46 UTC, merged