chore： 添加 DTK 单元测试任务
deepin-community/coding-quarter pull request #19
Opened 2022-11-11 09:49 UTC by Groveer

as title

Log:

2022-11-11 09:58 UTC, zccrs requested changes

2022-11-11 09:58 UTC, zccrs commented on 2.进阶难度/[单元测试]给dtk组件的单元测试查缺补漏/README.md
> +1. 此任务需要一些`qt`、`cmake`的基础
qt 改为 Qt, cmake 改为 CMake，专有名字的大小写也要注意一下

2022-11-11 09:58 UTC, zccrs commented on 2.进阶难度/[单元测试]给dtk组件的单元测试查缺补漏/README.md
> +
还应该列出来具体符合“DTK 组件”这个定义的项目地址，每一个url都列出来

2022-11-11 09:58 UTC, zccrs commented on 2.进阶难度/[单元测试]给dtk组件的单元测试查缺补漏/README.md
> +Issue 标题格式，DError 为存在缺漏的类：
issue可以做成模板，在提issue的那个界面搞一个单元测试问题的模板，实现方式可以谘询 @BLumia

2022-11-11 09:58 UTC, zccrs commented on 2.进阶难度/[单元测试]给dtk组件的单元测试查缺补漏/README.md
> +#### 在 Github 上提 PR
这个不用专门讲 coding-quarter/README.md 中已经统一说了，如果有针对dtk项目特别需要注意的这里能专门讲一下，否则就不需要了

2022-11-11 09:58 UTC, zccrs commented on 2.进阶难度/[单元测试]给dtk组件的单元测试查缺补漏/README.md
> +- [ ] 提交 PR 前必须先创建 Issue
还要说清楚issue是否有效也是会审核的，如果是无效的issue, 那跟没提交是等价的

2022-11-11 10:12 UTC, Groveer commented on 2.进阶难度/[单元测试]给dtk组件的单元测试查缺补漏/README.md
> +Issue 标题格式，DError 为存在缺漏的类：
先删除此章节，后续将 Issue 模板做出来

2022-11-14 02:44 UTC, zccrs approved these changes

2022-11-14 02:45 UTC, merged