feat: add dci-tool task
deepin-community/coding-quarter pull request #2
Opened 2022-11-07 07:52 UTC by kegechen

add dci-tool task

Log: add task

2022-11-07 08:24 UTC, zccrs requested changes

2022-11-07 08:24 UTC, zccrs commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/README.md
> +基于 `DTK` 完成一个可以生成 `DCI` 格式图标的小工具
可以固定限制使用 dtkgui 和 dtkdeclarative

2022-11-07 08:24 UTC, zccrs commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/README.md
> +由于 `DCI` 图标是开发特性，故在 `uos` / `deepin` 上还未集成，请自行编译打包安装 `dtkcore` / `dtkgui` / `dtkdeclarative` 。为方便起见，下述步骤假定您在使用 `deepin` 或者 `uos` 开启了开发者模式，并有管理员权限。
不用给出那么多的可选环境，直接缺省为 deepin V20 latest 版本就行了。对于不熟悉我们版本关系的人来说，给出了多个选择反而不知道应该选哪个，所以不用提uos，固定用deepin就行了，避免有不必要的问题。

2022-11-07 08:24 UTC, zccrs commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/README.md
> +    - [ ] 项目用 CMake 管理，Gui(建议使用qml) 程序基于 DTK （必须满足）
不用写建议，明确要求界面使用dtkdeclarative，用qml编写

2022-11-07 08:24 UTC, zccrs commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/README.md
> +    - [ ] 项目包含 README、LICENSE等文档（必须满足）
直接写符合开源合规要求就行，这个要求有个专门的文档，在外部可见，这里可以引用链接，可以问下 @BLumia 。

2022-11-07 08:24 UTC, zccrs commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/README.md
> +    - 此项目需要您最终将代码提交到 deepin-community 仓库之中
自研项目应该是放到  linuxdeepin 中

2022-11-07 08:24 UTC, zccrs commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/README.md
> +    - 对于 `dci-tool` 的开发，可以直接在您自己的帐号下新建仓库进行开发。
提前在 liunxudeepin 建好项目，走PR的流程提交到这个项目。

2022-11-07 08:24 UTC, zccrs commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/DCI图标介绍.md
> +# 一、DCI图标介绍
把 dci 文件格式的标准文档也放过来

2022-11-07 08:24 UTC, zccrs commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/README.md
> +基于 `DTK` 完成一个可以生成 `DCI` 格式图标的小工具
这里写的太模糊了，可以参考产品需求描述那样写，另外有设计图，要附上来

2022-11-07 10:03 UTC, kegechen commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/DCI图标介绍.md
> +# 一、DCI图标介绍
图标介绍中包含了

2022-11-07 10:08 UTC, kegechen commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/README.md
> +    - [ ] 项目用 CMake 管理，Gui(建议使用qml) 程序基于 DTK （必须满足）
ok

2022-11-08 01:06 UTC, kegechen commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/README.md
> +    - 此项目需要您最终将代码提交到 deepin-community 仓库之中
done

2022-11-08 01:12 UTC, kegechen commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/README.md
> +    - 对于 `dci-tool` 的开发，可以直接在您自己的帐号下新建仓库进行开发。
linuxdeepin/dci-tool 已经创建

2022-11-08 01:12 UTC, kegechen commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/README.md
> +由于 `DCI` 图标是开发特性，故在 `uos` / `deepin` 上还未集成，请自行编译打包安装 `dtkcore` / `dtkgui` / `dtkdeclarative` 。为方便起见，下述步骤假定您在使用 `deepin` 或者 `uos` 开启了开发者模式，并有管理员权限。
deepin

2022-11-08 01:13 UTC, kegechen commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/README.md
> +基于 `DTK` 完成一个可以生成 `DCI` 格式图标的小工具
需求描述再整理一下，设计图在和设计沟通，之前的设计图有点问题， 着重点是批量处理，对生成单个dci图标没有设计

2022-11-08 02:43 UTC, zccrs requested changes

2022-11-08 02:43 UTC, zccrs commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/DCI图标介绍.md
> +**（1） 部分接口介绍（其余接口可询问DTK开发）：**
这句话写在这里没用，可以改成有问题可以到开发者邮件列表询问

2022-11-08 08:20 UTC, kegechen commented on 2.进阶难度/[开发应用]DCI图标小工具(dci-tool)/DCI图标介绍.md
> +**（1） 部分接口介绍（其余接口可询问DTK开发）：**
done

2022-11-09 05:22 UTC, zccrs approved these changes

2022-11-09 05:22 UTC, merged