chore: 添加 dde-nixos 相关任务
deepin-community/coding-quarter pull request #35
Opened 2022-12-01 09:29 UTC by wineee

2022-12-05 06:02 UTC, zccrs requested changes

2022-12-05 06:02 UTC, zccrs commented on 2.进阶难度/[DDE移植]完善dde-nixos/README.md
> +预计用时：1 天
这个时间要重新考虑下，对于新手来说1天估计不够

2022-12-05 06:02 UTC, zccrs commented on 2.进阶难度/[DDE移植]完善dde-nixos/README.md
> +#### 任务分类三：
同上

2022-12-05 06:19 UTC, wineee commented on 2.进阶难度/[DDE移植]完善dde-nixos/README.md
> +预计用时：1 天
nix 构建镜像有一些 tricks, 这个任务难度还是不高的

2022-12-05 06:22 UTC, wineee commented on 2.进阶难度/[DDE移植]完善dde-nixos/README.md
> +预计用时：1 小时
我把分类1,3合并，这个和分类3一起加上学习的时间 ，
分类 2 单独分出去

2022-12-05 07:42 UTC, zccrs commented on 2.进阶难度/[DDE移植]完善dde-nixos/README.md
> +#### 任务分类一：
这个标题还需要吗

2022-12-05 07:47 UTC, wineee commented on 2.进阶难度/[DDE移植]完善dde-nixos/README.md
> +#### 任务分类一：
没必要了

2022-12-05 07:50 UTC, zccrs approved these changes

2022-12-07 02:31 UTC, merged

2022-12-07 02:40 UTC, wineee commented
我想把 live CD 任务时间延长下，已经改了，但是我实际升到 v23 后， ssh 配置有问题，代理也有点麻烦，没能提交上来