Add Qt bug task.
deepin-community/coding-quarter pull request #4
Opened 2022-11-08 05:20 UTC by Dami-star

2022-11-08 05:47 UTC, zccrs requested changes

2022-11-08 05:47 UTC, zccrs commented on 1.普通难度/[找BUG]Qt-Bug查找/README.md
> +此任务的导师为： luyaning@uniontech.com
不用描述为导师，准确的说是“任务对接人”，主要负责对任务有疑问时答疑、对任务成果验收，不承担导师职责

2022-11-08 05:50 UTC, Dami-star commented on 1.普通难度/[找BUG]Qt-Bug查找/README.md
> +此任务的导师为： luyaning@uniontech.com
已修改

2022-11-08 06:07 UTC, zccrs requested changes

2022-11-08 06:07 UTC, zccrs commented on 1.普通难度/[找BUG]Qt-Bug查找/README.md
> +​	使用deepin v20系统上提供Qt5、Qt6基础环境，参考https://bugreports.qt.io/ 或 https://forum.qt.io/ 查找Qt bug，基于qtcreator编写demo在deepin上测试系统提供Qt5、Qt6是否存在Qt bug，如果存在提交发现Qt bug与复现demo。
专有名词要注意一下，使用 QtCreator

2022-11-08 06:07 UTC, zccrs commented on 1.普通难度/[找BUG]Qt-Bug查找/README.md
> +sudo apt-get install qtbase6-dev  //Qt6
这个步骤应该还缺少一些，qtbase 的包里是不带 qtcreator 的，需要单独安装，包括 gcc gdb 等工具

2022-11-08 06:07 UTC, zccrs commented on 1.普通难度/[找BUG]Qt-Bug查找/README.md
> +根据发现问题在对应项目上新建issues，并按照以下格式提交发现的bug：
对于问题的模板，可以对应的github项目的issue上加模板，这里只需要写按issue模板提交就行。
另外我理解这个任务的验收标准应该包含“Bug 真实有效，且上游最新代码中还未修复”的要求

2022-11-08 06:07 UTC, zccrs commented on 1.普通难度/[找BUG]Qt-Bug查找/README.md
> +### 验收标准
跟上面重复了，标题一样

2022-11-08 07:08 UTC, zccrs requested changes

2022-11-08 07:08 UTC, zccrs commented on 1.普通难度/[找BUG]Qt-Bug查找/README.md
> +sudo apt build-deb qtcreator //注意配置源deb-src
apt build-dep ?

2022-11-08 07:11 UTC, Dami-star commented on 1.普通难度/[找BUG]Qt-Bug查找/README.md
> +sudo apt build-deb qtcreator //注意配置源deb-src
build-dep可以省去开发者 手动搭建依赖环境

2022-11-08 07:15 UTC, zccrs commented on 1.普通难度/[找BUG]Qt-Bug查找/README.md
> +sudo apt build-deb qtcreator //注意配置源deb-src
文章里写成了 apt build-deb

2022-11-08 07:17 UTC, Dami-star commented on 1.普通难度/[找BUG]Qt-Bug查找/README.md
> +sudo apt build-deb qtcreator //注意配置源deb-src
尴尬了

2022-11-09 03:49 UTC, zccrs approved these changes

2022-11-09 03:49 UTC, merged